name: Bitcoin Search
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libprocps-dev
          git clone https://github.com/brichard19/BitCrack.git
          cd BitCrack
          make

      - name: Run Search
        run: |
          # अब हम सीधे फोल्डर के अंदर जाकर कमांड चलाएंगे
          cd BitCrack
          chmod +x BitCrack
          ./BitCrack --keyspace 40000000000000000:7ffffffffffffffff --address 1PWo3JeB9jrGwfHDNpdGK54CRas7fsVzXU -r
